<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CardMarketExpansionsSeed extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $expansions = [
            ["id" => 1606, "name" => "\"W\" Promos",'scraper_provider_id' => 2],
            ["id" => 4310, "name" => "10th Movie Commemoration Set",'scraper_provider_id' => 2],
            ["id" => 4299, "name" => "11th Movie Commemoration Set",'scraper_provider_id' => 2],
            ["id" => 5402, "name" => "151",'scraper_provider_id' => 2],
            ["id" => 4345, "name" => "25th Anniversary Collection",'scraper_provider_id' => 2],
            ["id" => 4346, "name" => "25th Anniversary Edition",'scraper_provider_id' => 2],
            ["id" => 4389, "name" => "25th Anniversary Golden Box",'scraper_provider_id' => 2],
            ["id" => 6514, "name" => "30th Anniversary Celebration Simplified Chinese",'scraper_provider_id' => 2],
            ["id" => 5877, "name" => "ADV Expansion Pack",'scraper_provider_id' => 2],
            ["id" => 4350, "name" => "ADV Promos",'scraper_provider_id' => 2],
            ["id" => 4280, "name" => "Advent of Arceus",'scraper_provider_id' => 2],
            ["id" => 6168, "name" => "Adventure Special Pack",'scraper_provider_id' => 2],
            ["id" => 3951, "name" => "Alolan Moonlight",'scraper_provider_id' => 2],
            ["id" => 3801, "name" => "Alter Genesis",'scraper_provider_id' => 2],
            ["id" => 1660, "name" => "Ancient Origins",'scraper_provider_id' => 2],
            ["id" => 5478, "name" => "Ancient Roar",'scraper_provider_id' => 2],
            ["id" => 5867, "name" => "Aqua Deck Kit",'scraper_provider_id' => 2],
            ["id" => 1537, "name" => "Aquapolis",'scraper_provider_id' => 2],
            ["id" => 1565, "name" => "Arceus",'scraper_provider_id' => 2],
            ["id" => 6368, "name" => "Arceus & Dialga & Palkia GX Premium Deck Building Box",'scraper_provider_id' => 2],
            ["id" => 4279, "name" => "Arceus LV.X Deck: Grass & Fire",'scraper_provider_id' => 2],
            ["id" => 4278, "name" => "Arceus LV.X Deck: Lightning & Psychic",'scraper_provider_id' => 2],
            ["id" => 6395, "name" => "Ascended Heroes",'scraper_provider_id' => 2],
            ["id" => 6455, "name" => "Ascended Heroes: Additionals",'scraper_provider_id' => 2],
            ["id" => 3974, "name" => "Ash vs Team Rocket Deck Kit",'scraper_provider_id' => 2],
            ["id" => 4979, "name" => "Astral Radiance",'scraper_provider_id' => 2],
            ["id" => 3926, "name" => "Awakened Heroes",'scraper_provider_id' => 2],
            ["id" => 4508, "name" => "Awakening Legends",'scraper_provider_id' => 2],
            ["id" => 4004, "name" => "Awakening Psychic King",'scraper_provider_id' => 2],
            ["id" => 6250, "name" => "Azure Shadow - Pursuit",'scraper_provider_id' => 2],
            ["id" => 6249, "name" => "Azure Shadow - Roar",'scraper_provider_id' => 2],
            ["id" => 4024, "name" => "Bandit Ring",'scraper_provider_id' => 2],
            ["id" => 5021, "name" => "Base Expansion Pack",'scraper_provider_id' => 2],
            ["id" => 1523, "name" => "Base Set",'scraper_provider_id' => 2],
            ["id" => 1527, "name" => "Base Set 2",'scraper_provider_id' => 2],
            ["id" => 4316, "name" => "Bastiodon the Defender",'scraper_provider_id' => 2],
            ["id" => 6200, "name" => "Battle Academy 2020",'scraper_provider_id' => 2],
            ["id" => 6199, "name" => "Battle Academy 2022",'scraper_provider_id' => 2],
            ["id" => 5890, "name" => "Battle Academy 2024",'scraper_provider_id' => 2],
            ["id" => 6314, "name" => "Battle Elite",'scraper_provider_id' => 2],
            ["id" => 4205, "name" => "Battle Gift Set: Thundurus vs Tornadus",'scraper_provider_id' => 2],
            ["id" => 5738, "name" => "Battle Master Deck Chien-Pao ex",'scraper_provider_id' => 2],
            ["id" => 5737, "name" => "Battle Master Deck Tera Charizard ex",'scraper_provider_id' => 2],
            ["id" => 5996, "name" => "Battle Partners",'scraper_provider_id' => 2],
            ["id" => 5997, "name" => "Battle Partners Deck Build Box",'scraper_provider_id' => 2],
            ["id" => 6311, "name" => "Battle Party Dream Together",'scraper_provider_id' => 2],
            ["id" => 6310, "name" => "Battle Party Shining Dream",'scraper_provider_id' => 2],
            ["id" => 4441, "name" => "Battle Region",'scraper_provider_id' => 2],
            ["id" => 4212, "name" => "Battle Strength Decks",'scraper_provider_id' => 2],
            ["id" => 3675, "name" => "Battle Styles",'scraper_provider_id' => 2],
            ["id" => 4211, "name" => "Battle Theme Deck: Victini",'scraper_provider_id' => 2],
            ["id" => 4286, "name" => "Beat of the Frontier",'scraper_provider_id' => 2],
            ["id" => 4216, "name" => "Beginning Set",'scraper_provider_id' => 2],
            ["id" => 6510, "name" => "Beginning Set Pikachu",'scraper_provider_id' => 2],
            ["id" => 6509, "name" => "Beginning Set Plus",'scraper_provider_id' => 2],
            ["id" => 1605, "name" => "Best of Game Cards Promos",'scraper_provider_id' => 2],
            ["id" => 1571, "name" => "Black & White",'scraper_provider_id' => 2],
            ["id" => 6287, "name" => "Black & White ID/TH",'scraper_provider_id' => 2],
            ["id" => 6134, "name" => "Black Bolt",'scraper_provider_id' => 2],
            ["id" => 6130, "name" => "Black Bolt JP",'scraper_provider_id' => 2],
            ["id" => 6222, "name" => "Black Bolt JP: Additionals",'scraper_provider_id' => 2],
            ["id" => 6197, "name" => "Black Bolt: Additionals",'scraper_provider_id' => 2],
            ["id" => 4214, "name" => "Black Collection",'scraper_provider_id' => 2],
            ["id" => 5726, "name" => "Black Deck Kit",'scraper_provider_id' => 2],
            ["id" => 4190, "name" => "Black Kyurem EX Battle Strength Deck",'scraper_provider_id' => 2],
            ["id" => 6416, "name" => "Blade Awakening",'scraper_provider_id' => 2],
            ["id" => 4181, "name" => "Blastoise + Kyurem EX Combo Deck",'scraper_provider_id' => 2],
            ["id" => 4270, "name" => "Blastoise Battle Starter Deck",'scraper_provider_id' => 2],
            ["id" => 4014, "name" => "Blue Shock",'scraper_provider_id' => 2],
            ["id" => 4330, "name" => "Blue Sky Stream",'scraper_provider_id' => 2],
            ["id" => 6415, "name" => "Bonds of Destiny",'scraper_provider_id' => 2],
            ["id" => 4289, "name" => "Bonds to the End of Time",'scraper_provider_id' => 2],
            ["id" => 6169, "name" => "Bonus Round",'scraper_provider_id' => 2],
            ["id" => 1577, "name" => "Boundaries Crossed",'scraper_provider_id' => 2],
            ["id" => 6258, "name" => "Brave Stars - Brave",'scraper_provider_id' => 2],
            ["id" => 6257, "name" => "Brave Stars - Charm",'scraper_provider_id' => 2],
            ["id" => 6398, "name" => "Brave Stars Deck Building Gift Box",'scraper_provider_id' => 2],
            ["id" => 4089, "name" => "BREAK Starter Pack",'scraper_provider_id' => 2],
            ["id" => 1687, "name" => "BREAKpoint",'scraper_provider_id' => 2],
            ["id" => 1678, "name" => "BREAKthrough",'scraper_provider_id' => 2],
            ["id" => 6276, "name" => "Brilliant Counterattack",'scraper_provider_id' => 2],
            ["id" => 6495, "name" => "Brilliant Fantasy",'scraper_provider_id' => 2],
            ["id" => 4434, "name" => "Brilliant Stars",'scraper_provider_id' => 2],
            ["id" => 1622, "name" => "Burger King DP Promos 2008",'scraper_provider_id' => 2],
            ["id" => 5034, "name" => "Burger King Platinum Promos 2009",'scraper_provider_id' => 2],
            ["id" => 1824, "name" => "Burning Shadows",'scraper_provider_id' => 2],
            ["id" => 1611, "name" => "BW Black Star Promos",'scraper_provider_id' => 2],
            ["id" => 4218, "name" => "BW Promos",'scraper_provider_id' => 2],
            ["id" => 1630, "name" => "BW Trainer Kit",'scraper_provider_id' => 2],
            ["id" => 1570, "name" => "Call of Legends",'scraper_provider_id' => 2],
            ["id" => 4347, "name" => "Celebrations",'scraper_provider_id' => 2],
            ["id" => 2320, "name" => "Celestial Storm",'scraper_provider_id' => 2],
            ["id" => 4467, "name" => "Challenge from the Darkness",'scraper_provider_id' => 2],
            ["id" => 3886, "name" => "Champion Road",'scraper_provider_id' => 2],
            ["id" => 3419, "name" => "Champion’s Path",'scraper_provider_id' => 2],
            ["id" => 4284, "name" => "Charizard SP Half Deck",'scraper_provider_id' => 2],
            ["id" => 4174, "name" => "Chilling Reign",'scraper_provider_id' => 2],
            ["id" => 4293, "name" => "Chimchar DPt Half Deck",'scraper_provider_id' => 2],
            ["id" => 4261, "name" => "Clash at the Summit",'scraper_provider_id' => 2],
            ["id" => 5713, "name" => "Clash of the Blue Sky",'scraper_provider_id' => 2],
            ["id" => 5315, "name" => "Clay Burst",'scraper_provider_id' => 2],
            ["id" => 4194, "name" => "Cold Flare",'scraper_provider_id' => 2],
            ["id" => 6099, "name" => "Collect 151",'scraper_provider_id' => 2],
            ["id" => 3966, "name" => "Collection Moon",'scraper_provider_id' => 2],
            ["id" => 4217, "name" => "Collection Sheet Journey Partners",'scraper_provider_id' => 2],
            ["id" => 3971, "name" => "Collection Sun",'scraper_provider_id' => 2],
            ["id" => 4064, "name" => "Collection X",'scraper_provider_id' => 2],
            ["id" => 4059, "name" => "Collection Y",'scraper_provider_id' => 2],
            ["id" => 2644, "name" => "Cosmic Eclipse",'scraper_provider_id' => 2],
            ["id" => 5636, "name" => "Crimson Haze",'scraper_provider_id' => 2],
            ["id" => 1843, "name" => "Crimson Invasion",'scraper_provider_id' => 2],
            ["id" => 4507, "name" => "Crossing the Ruins...",'scraper_provider_id' => 2],
            ["id" => 5201, "name" => "Crown Zenith",'scraper_provider_id' => 2],
            ["id" => 3994, "name" => "Cruel Traitor",'scraper_provider_id' => 2],
            ["id" => 4305, "name" => "Cry from the Mysterious",'scraper_provider_id' => 2],
            ["id" => 5574, "name" => "Cyber Judge",'scraper_provider_id' => 2],
            ["id" => 6237, "name" => "Dark Crystal Blaze",'scraper_provider_id' => 2],
            ["id" => 1575, "name" => "Dark Explorers",'scraper_provider_id' => 2],
            ["id" => 3861, "name" => "Dark Order",'scraper_provider_id' => 2],
            ["id" => 5048, "name" => "Dark Phantasma",'scraper_provider_id' => 2],
            ["id" => 4204, "name" => "Dark Rush",'scraper_provider_id' => 2],
            ["id" => 3199, "name" => "Darkness Ablaze",'scraper_provider_id' => 2],
            ["id" => 3936, "name" => "Darkness that Consumes Light",'scraper_provider_id' => 2],
            ["id" => 4509, "name" => "Darkness, and to Light...",'scraper_provider_id' => 2],
            ["id" => 4308, "name" => "Dawn Dash",'scraper_provider_id' => 2],
            ["id" => 5728, "name" => "Deoxys Constructed Starter Deck",'scraper_provider_id' => 2],
            ["id" => 6096, "name" => "Destined Rivals",'scraper_provider_id' => 2],
            ["id" => 6140, "name" => "Destined Rivals: Additionals",'scraper_provider_id' => 2],
            ["id" => 2438, "name" => "Detective Pikachu",'scraper_provider_id' => 2],
            ["id" => 4295, "name" => "Dialga DPt Half Deck",'scraper_provider_id' => 2],
            ["id" => 4300, "name" => "Dialga Half Deck",'scraper_provider_id' => 2],
            ["id" => 4312, "name" => "Dialga LV.X Constructed Standard Deck",'scraper_provider_id' => 2],
            ["id" => 1555, "name" => "Diamond & Pearl",'scraper_provider_id' => 2],
            ["id" => 6350, "name" => "Display Set Gift Box Gengar",'scraper_provider_id' => 2],
            ["id" => 3836, "name" => "Double Blaze",'scraper_provider_id' => 2],
            ["id" => 1648, "name" => "Double Crisis",'scraper_provider_id' => 2],
            ["id" => 1609, "name" => "DP Black Star Promos",'scraper_provider_id' => 2],
            ["id" => 4322, "name" => "DP Promos",'scraper_provider_id' => 2],
            ["id" => 1628, "name" => "DP Trainer Kit",'scraper_provider_id' => 2],
            ["id" => 4298, "name" => "DPt Promos",'scraper_provider_id' => 2],
            ["id" => 4200, "name" => "Dragon Blade",'scraper_provider_id' => 2],
            ["id" => 4201, "name" => "Dragon Blast",'scraper_provider_id' => 2],
            ["id" => 2351, "name" => "Dragon Majesty",'scraper_provider_id' => 2],
            ["id" => 4203, "name" => "Dragon Selection",'scraper_provider_id' => 2],
            ["id" => 3891, "name" => "Dragon Storm",'scraper_provider_id' => 2],
            ["id" => 1636, "name" => "Dragon Vault",'scraper_provider_id' => 2],
            ["id" => 1576, "name" => "Dragons Exalted",'scraper_provider_id' => 2],
            ["id" => 3806, "name" => "Dream League",'scraper_provider_id' => 2],
            ["id" => 6298, "name" => "Dynamax Clash - Flame",'scraper_provider_id' => 2],
            ["id" => 6297, "name" => "Dynamax Clash - Thunder",'scraper_provider_id' => 2],
            ["id" => 6288, "name" => "Dynamax Tactics",'scraper_provider_id' => 2],
            ["id" => 5698, "name" => "Earth's Groudon ex Constructed Starter Deck",'scraper_provider_id' => 2],
            ["id" => 6401, "name" => "Eevee Advanced Gift Box",'scraper_provider_id' => 2],
            ["id" => 4250, "name" => "Eevee GX Starter Sets",'scraper_provider_id' => 2],
            ["id" => 4239, "name" => "Eevee Heroes",'scraper_provider_id' => 2],
            ["id" => 4240, "name" => "Eevee Heroes VMAX Special Set",'scraper_provider_id' => 2],
            ["id" => 6367, "name" => "Eeveelutions GX Gift Box",'scraper_provider_id' => 2],
            ["id" => 4238, "name" => "Emboar EX vs Togekiss EX Deck Kit",'scraper_provider_id' => 2],
            ["id" => 4029, "name" => "Emerald Break",'scraper_provider_id' => 2],
            ["id" => 1572, "name" => "Emerging Powers",'scraper_provider_id' => 2],
            ["id" => 4306, "name" => "Entry Pack '08",'scraper_provider_id' => 2],
            ["id" => 6193, "name" => "Eternal Birth",'scraper_provider_id' => 2],
            ["id" => 4187, "name" => "Everyone's Exciting Battle",'scraper_provider_id' => 2],
            ["id" => 1742, "name" => "Evolutions",'scraper_provider_id' => 2],
            ["id" => 4328, "name" => "Evolving Skies",'scraper_provider_id' => 2],
            ["id" => 4180, "name" => "EX Battle Boost",'scraper_provider_id' => 2],
            ["id" => 1552, "name" => "EX Crystal Guardians",'scraper_provider_id' => 2],
            ["id" => 1549, "name" => "EX Delta Species",'scraper_provider_id' => 2],
            ["id" => 1546, "name" => "EX Deoxys",'scraper_provider_id' => 2],
            ["id" => 1541, "name" => "EX Dragon",'scraper_provider_id' => 2],
            ["id" => 1553, "name" => "EX Dragon Frontiers",'scraper_provider_id' => 2],
            ["id" => 1547, "name" => "EX Emerald",'scraper_provider_id' => 2],
            ["id" => 1544, "name" => "EX FireRed & LeafGreen",'scraper_provider_id' => 2],
            ["id" => 1543, "name" => "EX Hidden Legends",'scraper_provider_id' => 2],
            ["id" => 1551, "name" => "EX Holon Phantoms",'scraper_provider_id' => 2],
            ["id" => 1550, "name" => "EX Legend Maker",'scraper_provider_id' => 2],
            ["id" => 1554, "name" => "EX Power Keepers",'scraper_provider_id' => 2],
            ["id" => 1539, "name" => "EX Ruby & Sapphire",'scraper_provider_id' => 2],
            ["id" => 1540, "name" => "EX Sandstorm",'scraper_provider_id' => 2],
            ["id" => 5362, "name" => "ex Start Decks",'scraper_provider_id' => 2],
            ["id" => 5219, "name" => "ex Starter Set Fuecoco & Ampharos ex",'scraper_provider_id' => 2],
            ["id" => 5299, "name" => "ex Starter Set Pikachu ex & Pawmot",'scraper_provider_id' => 2],
            ["id" => 5220, "name" => "ex Starter Set Quaxly & Mimikyu ex",'scraper_provider_id' => 2],
            ["id" => 5218, "name" => "ex Starter Set Sprigatito & Lucario ex",'scraper_provider_id' => 2],
            ["id" => 1542, "name" => "EX Team Magma vs Team Aqua",'scraper_provider_id' => 2],
            ["id" => 1545, "name" => "EX Team Rocket Returns",'scraper_provider_id' => 2],
            ["id" => 1626, "name" => "EX Trainer Kit",'scraper_provider_id' => 2],
            ["id" => 1627, "name" => "EX Trainer Kit 2",'scraper_provider_id' => 2],
            ["id" => 1548, "name" => "EX Unseen Forces",'scraper_provider_id' => 2],
            ["id" => 4169, "name" => "Expansion Pack",'scraper_provider_id' => 2],
            ["id" => 3989, "name" => "Expansion Pack 20th Anniversary",'scraper_provider_id' => 2],
            ["id" => 3781, "name" => "Expansion Sheet",'scraper_provider_id' => 2],
            ["id" => 1536, "name" => "Expedition Base Set",'scraper_provider_id' => 2],
            ["id" => 3219, "name" => "Explosive Flame Walker",'scraper_provider_id' => 2],
            ["id" => 4490, "name" => "Extra Regulation Box",'scraper_provider_id' => 2],
            ["id" => 3946, "name" => "Facing a New Trial",'scraper_provider_id' => 2],
            ["id" => 3871, "name" => "Fairy Rise",'scraper_provider_id' => 2],
            ["id" => 1706, "name" => "Fates Collide",'scraper_provider_id' => 2],
            ["id" => 6110, "name" => "Fearless Terastal",'scraper_provider_id' => 2],
            ["id" => 5720, "name" => "Feraligatr Constructed Starter Deck",'scraper_provider_id' => 2],
            ["id" => 3999, "name" => "Fever-Burst Fighter",'scraper_provider_id' => 2],
            ["id" => 6252, "name" => "Final Flame Dance",'scraper_provider_id' => 2],
            ["id" => 1583, "name" => "Flashfire",'scraper_provider_id' => 2],
            ["id" => 5714, "name" => "Flight of Legends",'scraper_provider_id' => 2],
            ["id" => 5871, "name" => "Flygon Constructed Starter Deck",'scraper_provider_id' => 2],
            ["id" => 2075, "name" => "Forbidden Light",'scraper_provider_id' => 2],
            ["id" => 3896, "name" => "Forbidden Light JP",'scraper_provider_id' => 2],
            ["id" => 1526, "name" => "Fossil",'scraper_provider_id' => 2],
            ["id" => 6347, "name" => "Four-Party Connection Gift Box",'scraper_provider_id' => 2],
            ["id" => 4195, "name" => "Freeze Bolt",'scraper_provider_id' => 2],
            ["id" => 3841, "name" => "Full Metal Wall",'scraper_provider_id' => 2],
            ["id" => 1584, "name" => "Furious Fists",'scraper_provider_id' => 2],
            ["id" => 4360, "name" => "Fusion Arts",'scraper_provider_id' => 2],
            ["id" => 4382, "name" => "Fusion Strike",'scraper_provider_id' => 2],
            ["id" => 3510, "name" => "Futsal Promos",'scraper_provider_id' => 2],
            ["id" => 5479, "name" => "Future Flash",'scraper_provider_id' => 2],
            ["id" => 4039, "name" => "Gaia Volcano",'scraper_provider_id' => 2],
            ["id" => 4297, "name" => "Galactic's Conquest",'scraper_provider_id' => 2],
            ["id" => 4287, "name" => "Gallade SP Half Deck",'scraper_provider_id' => 2],
            ["id" => 4198, "name" => "Garchomp Half Deck",'scraper_provider_id' => 2],
            ["id" => 4285, "name" => "Garchomp SP Half Deck",'scraper_provider_id' => 2],
            ["id" => 6001, "name" => "Gem Pack",'scraper_provider_id' => 2],
            ["id" => 6111, "name" => "Gem Pack Vol. 2",'scraper_provider_id' => 2],
            ["id" => 6292, "name" => "Gem Pack Vol. 3",'scraper_provider_id' => 2],
            ["id" => 6447, "name" => "Gem Pack Vol. 4",'scraper_provider_id' => 2],
            ["id" => 1693, "name" => "Generations",'scraper_provider_id' => 2],
            ["id" => 5927, "name" => "Generations Start Decks",'scraper_provider_id' => 2],
            ["id" => 4241, "name" => "Gengar VMAX High-Class Deck",'scraper_provider_id' => 2],
            ["id" => 3831, "name" => "GG End",'scraper_provider_id' => 2],
            ["id" => 5724, "name" => "Gift Box Emerald",'scraper_provider_id' => 2],
            ["id" => 5866, "name" => "Gift Box Latias ex",'scraper_provider_id' => 2],
            ["id" => 5865, "name" => "Gift Box Latios ex",'scraper_provider_id' => 2],
            ["id" => 4361, "name" => "Gift Box Mew • Lucario",'scraper_provider_id' => 2],
            ["id" => 4296, "name" => "Giratina DPt Half Deck",'scraper_provider_id' => 2],
            ["id" => 4301, "name" => "Giratina Half Deck",'scraper_provider_id' => 2],
            ["id" => 6301, "name" => "Giratina VSTAR Deck Building Gift Box",'scraper_provider_id' => 2],
            ["id" => 4506, "name" => "Gold, Silver, to a New World...",'scraper_provider_id' => 2],
            ["id" => 5711, "name" => "Golden Sky, Silvery Ocean",'scraper_provider_id' => 2],
            ["id" => 4099, "name" => "Golduck BREAK + Palkia EX Combo Deck",'scraper_provider_id' => 2],
            ["id" => 3826, "name" => "Great Detective Pikachu",'scraper_provider_id' => 2],
            ["id" => 1558, "name" => "Great Encounters",'scraper_provider_id' => 2],
            ["id" => 1800, "name" => "Guardians Rising",'scraper_provider_id' => 2],
            ["id" => 5686, "name" => "Guren Town Gym",'scraper_provider_id' => 2],
            ["id" => 3916, "name" => "GX Battle Boost",'scraper_provider_id' => 2],
            ["id" => 4251, "name" => "GX Starter Decks",'scraper_provider_id' => 2],
            ["id" => 3856, "name" => "GX Ultra Shiny",'scraper_provider_id' => 2],
            ["id" => 1530, "name" => "Gym Challenge",'scraper_provider_id' => 2],
            ["id" => 1529, "name" => "Gym Heroes",'scraper_provider_id' => 2],
            ["id" => 4208, "name" => "Hail Blizzard",'scraper_provider_id' => 2],
            ["id" => 5682, "name" => "Hanada City Gym",'scraper_provider_id' => 2],
            ["id" => 6309, "name" => "Happy Set Altaria & Latios & Infernape & Maushold",'scraper_provider_id' => 2],
            ["id" => 6334, "name" => "Happy Set Lucario & Greninja & Zamazenta & Mabosstiff",'scraper_provider_id' => 2],
            ["id" => 6335, "name" => "Happy Set Pikachu & Clefairy & Turtwig & Gimmighoul",'scraper_provider_id' => 2],
            ["id" => 1566, "name" => "HeartGold & SoulSilver",'scraper_provider_id' => 2],
            ["id" => 4273, "name" => "HeartGold Collection",'scraper_provider_id' => 2],
            ["id" => 6037, "name" => "Heat Wave Arena",'scraper_provider_id' => 2],
            ["id" => 4303, "name" => "Heatran vs Regigigas Deck Kit",'scraper_provider_id' => 2],
            ["id" => 1610, "name" => "HGSS Black Star Promos",'scraper_provider_id' => 2],
            ["id" => 2514, "name" => "Hidden Fates",'scraper_provider_id' => 2],
            ["id" => 5703, "name" => "Holon Phantom",'scraper_provider_id' => 2],
            ["id" => 5709, "name" => "Holon Research Tower",'scraper_provider_id' => 2],
            ["id" => 5717, "name" => "Holon Research Tower Fire Quarter Deck",'scraper_provider_id' => 2],
            ["id" => 5715, "name" => "Holon Research Tower Lightning Quarter Deck",'scraper_provider_id' => 2],
            ["id" => 5716, "name" => "Holon Research Tower Water Quarter Deck",'scraper_provider_id' => 2],
            ["id" => 1629, "name" => "HS Trainer Kit",'scraper_provider_id' => 2],
            ["id" => 4199, "name" => "Hydreigon Half Deck",'scraper_provider_id' => 2],
            ["id" => 4134, "name" => "Hyper Metal Chain Deck",'scraper_provider_id' => 2],
            ["id" => 5695, "name" => "Imprison! Gardevoir ex Constructed Standard Deck",'scraper_provider_id' => 2],
            ["id" => 5127, "name" => "Incandescent Arcana",'scraper_provider_id' => 2],
            ["id" => 6417, "name" => "Indigo Flame",'scraper_provider_id' => 2],
            ["id" => 4288, "name" => "Infernape SP Half Deck",'scraper_provider_id' => 2],
            ["id" => 6291, "name" => "Inferno X",'scraper_provider_id' => 2],
            ["id" => 3274, "name" => "Infinity Zone",'scraper_provider_id' => 2],
            ["id" => 4242, "name" => "Inteleon VMAX High-Class Deck",'scraper_provider_id' => 2],
            ["id" => 4302, "name" => "Intense Fight in the Destroyed Sky",'scraper_provider_id' => 2],
            ["id" => 5059, "name" => "Intro Pack Bulbasaur",'scraper_provider_id' => 2],
            ["id" => 5061, "name" => "Intro Pack Neo Chikorita",'scraper_provider_id' => 2],
            ["id" => 5062, "name" => "Intro Pack Neo Totodile",'scraper_provider_id' => 2],
            ["id" => 5060, "name" => "Intro Pack Squirtle",'scraper_provider_id' => 2],
            ["id" => 3956, "name" => "Islands Await You",'scraper_provider_id' => 2],
            ["id" => 4352, "name" => "J Promos",'scraper_provider_id' => 2],
            ["id" => 4172, "name" => "Jet Black Spirit",'scraper_provider_id' => 2],
            ["id" => 6006, "name" => "Journey Together",'scraper_provider_id' => 2],
            ["id" => 6088, "name" => "Journey Together: Additionals",'scraper_provider_id' => 2],
            ["id" => 1525, "name" => "Jungle",'scraper_provider_id' => 2],
            ["id" => 4197, "name" => "Keldeo Battle Strength Deck",'scraper_provider_id' => 2],
            ["id" => 5683, "name" => "Kuchiba City Gym",'scraper_provider_id' => 2],
            ["id" => 4274, "name" => "L-P Promos",'scraper_provider_id' => 2],
            ["id" => 4466, "name" => "Leaders' Stadium",'scraper_provider_id' => 2],
            ["id" => 4266, "name" => "Leafeon Expert Deck",'scraper_provider_id' => 2],
            ["id" => 1535, "name" => "Legendary Collection",'scraper_provider_id' => 2],
            ["id" => 3384, "name" => "Legendary Heartbeat",'scraper_provider_id' => 2],
            ["id" => 4114, "name" => "Legendary Shine Collection",'scraper_provider_id' => 2],
            ["id" => 1581, "name" => "Legendary Treasures",'scraper_provider_id' => 2],
            ["id" => 1560, "name" => "Legends Awakened",'scraper_provider_id' => 2],
            ["id" => 6366, "name" => "Lillie's Support Gift Box",'scraper_provider_id' => 2],
            ["id" => 5094, "name" => "Lost Abyss",'scraper_provider_id' => 2],
            ["id" => 4262, "name" => "Lost Link",'scraper_provider_id' => 2],
            ["id" => 5093, "name" => "Lost Origin",'scraper_provider_id' => 2],
            ["id" => 2370, "name" => "Lost Thunder",'scraper_provider_id' => 2],
            ["id" => 5915, "name" => "M Master Deck Build Box Power Style",'scraper_provider_id' => 2],
            ["id" => 5914, "name" => "M Master Deck Build Box Speed Style",'scraper_provider_id' => 2],
            ["id" => 6393, "name" => "M-P Indonesian Promos",'scraper_provider_id' => 2],
            ["id" => 6230, "name" => "M-P Promos",'scraper_provider_id' => 2],
            ["id" => 6392, "name" => "M-P Thai Promos",'scraper_provider_id' => 2],
            ["id" => 6391, "name" => "M-P Traditional Chinese Promos",'scraper_provider_id' => 2],
            ["id" => 5868, "name" => "Magma Deck Kit",'scraper_provider_id' => 2],
            ["id" => 4124, "name" => "Magma Gang VS Aqua Gang: Double Crisis",'scraper_provider_id' => 2],
            ["id" => 5869, "name" => "Magma VS Aqua: Two Ambitions",'scraper_provider_id' => 2],
            ["id" => 4269, "name" => "Magmortar Battle Starter Deck",'scraper_provider_id' => 2],
            ["id" => 4307, "name" => "Magmortar vs Electivire Deck Kit",'scraper_provider_id' => 2],
            ["id" => 1559, "name" => "Majestic Dawn",'scraper_provider_id' => 2],
            ["id" => 5690, "name" => "Mask of Change",'scraper_provider_id' => 2],
            ["id" => 4191, "name" => "Master Deck Build Box EX",'scraper_provider_id' => 2],
            ["id" => 5718, "name" => "Master Kit",'scraper_provider_id' => 2],
            ["id" => 6442, "name" => "Master Strategy Deck Building Sets",'scraper_provider_id' => 2],
            ["id" => 3751, "name" => "Matchless Fighters",'scraper_provider_id' => 2],
            ["id" => 4079, "name" => "MAudino EX Mega Battle Deck",'scraper_provider_id' => 2],
            ["id" => 1623, "name" => "McDonald's Collection 2011",'scraper_provider_id' => 2],
            ["id" => 1624, "name" => "McDonald's Collection 2012",'scraper_provider_id' => 2],
            ["id" => 2352, "name" => "McDonald's Collection 2013",'scraper_provider_id' => 2],
            ["id" => 1625, "name" => "McDonald's Collection 2014",'scraper_provider_id' => 2],
            ["id" => 1741, "name" => "McDonald's Collection 2015",'scraper_provider_id' => 2],
            ["id" => 1752, "name" => "McDonald's Collection 2016",'scraper_provider_id' => 2],
            ["id" => 1845, "name" => "McDonald's Collection 2017",'scraper_provider_id' => 2],
            ["id" => 2404, "name" => "McDonald's Collection 2018",'scraper_provider_id' => 2],
            ["id" => 2361, "name" => "McDonald's Collection 2018 FR",'scraper_provider_id' => 2],
            ["id" => 2829, "name" => "McDonald's Collection 2019",'scraper_provider_id' => 2],
            ["id" => 3354, "name" => "McDonald's Collection 2019 FR",'scraper_provider_id' => 2],
            ["id" => 3738, "name" => "McDonald's Collection 25th Anniversary",'scraper_provider_id' => 2],
            ["id" => 5978, "name" => "McDonald's Dragon Discovery",'scraper_provider_id' => 2],
            ["id" => 5135, "name" => "McDonald's Match Battle 2022",'scraper_provider_id' => 2],
            ["id" => 5430, "name" => "McDonald's Match Battle 2023",'scraper_provider_id' => 2],
            ["id" => 4178, "name" => "McDonald's Pokémon-e Minimum Pack",'scraper_provider_id' => 2],
            ["id" => 4139, "name" => "MCharizard EX Mega Battle Deck",'scraper_provider_id' => 2],
            ["id" => 6189, "name" => "Mega Brave",'scraper_provider_id' => 2],
            ["id" => 6380, "name" => "MEGA Dream ex",'scraper_provider_id' => 2],
            ["id" => 6409, "name" => "MEGA Dream ex: Additionals",'scraper_provider_id' => 2],
            ["id" => 6209, "name" => "Mega Evolution",'scraper_provider_id' => 2],
            ["id" => 6324, "name" => "Mega Evolution Energies",'scraper_provider_id' => 2],
            ["id" => 6394, "name" => "Mega Evolution ID/TH",'scraper_provider_id' => 2],
            ["id" => 6231, "name" => "Mega Evolution Products",'scraper_provider_id' => 2],
            ["id" => 6290, "name" => "Mega Evolution: Additionals",'scraper_provider_id' => 2],
            ["id" => 6381, "name" => "MEGA Start Deck 100 Battle Collection",'scraper_provider_id' => 2],
            ["id" => 6382, "name" => "MEGA Start Deck 100 Battle Collection Corociao Version",'scraper_provider_id' => 2],
            ["id" => 6260, "name" => "MEGA Starter Set Mega Diancie ex",'scraper_provider_id' => 2],
            ["id" => 6259, "name" => "MEGA Starter Set Mega Gengar ex",'scraper_provider_id' => 2],
            ["id" => 6190, "name" => "Mega Symphonia",'scraper_provider_id' => 2],
            ["id" => 4182, "name" => "Megalo Cannon",'scraper_provider_id' => 2],
            ["id" => 5722, "name" => "Meganium Constructed Starter Deck",'scraper_provider_id' => 2],
            ["id" => 4277, "name" => "Melee! Pokémon Scramble",'scraper_provider_id' => 2],
            ["id" => 6406, "name" => "Meowth's Little Tricks",'scraper_provider_id' => 2],
            ["id" => 6232, "name" => "MEP Black Star Promos",'scraper_provider_id' => 2],
            ["id" => 5863, "name" => "Metagross Constructed Starter Deck",'scraper_provider_id' => 2],
            ["id" => 4267, "name" => "Metagross Expert Deck",'scraper_provider_id' => 2],
            ["id" => 6402, "name" => "Mew Confluence Deck Building Advanced Gift Box",'scraper_provider_id' => 2],
            ["id" => 4282, "name" => "Mewtwo LV.X Collection Pack",'scraper_provider_id' => 2],
            ["id" => 4179, "name" => "Mewtwo vs Genesect Deck Kit",'scraper_provider_id' => 2],
            ["id" => 5700, "name" => "Miracle Crystal",'scraper_provider_id' => 2],
            ["id" => 6121, "name" => "Miracle Journey",'scraper_provider_id' => 2],
            ["id" => 5873, "name" => "Miracle of the Desert",'scraper_provider_id' => 2],
            ["id" => 3816, "name" => "Miracle Twin",'scraper_provider_id' => 2],
            ["id" => 5710, "name" => "Mirage Forest",'scraper_provider_id' => 2],
            ["id" => 5719, "name" => "Mirage's Mew Constructed Starter Deck",'scraper_provider_id' => 2],
            ["id" => 4309, "name" => "Moonlit Pursuit",'scraper_provider_id' => 2],
            ["id" => 4276, "name" => "Movie Commemoration Random Pack",'scraper_provider_id' => 2],
            ["id" => 4348, "name" => "Movie Commemoration VS Pack",'scraper_provider_id' => 2],
            ["id" => 4339, "name" => "Movie Commemoration VS Pack: Aura's Lucario",'scraper_provider_id' => 2],
            ["id" => 4319, "name" => "Movie Commemoration VS Pack: Sea's Manaphy",'scraper_provider_id' => 2],
            ["id" => 4340, "name" => "Movie Commemoration VS Pack: Sky-Splitting Deoxys",'scraper_provider_id' => 2],
            ["id" => 4119, "name" => "MRayquaza EX Mega Battle Deck",'scraper_provider_id' => 2],
            ["id" => 5874, "name" => "Mudkip Constructed Starter Deck",'scraper_provider_id' => 2],
            ["id" => 5526, "name" => "My First Battle",'scraper_provider_id' => 2],
            ["id" => 5025, "name" => "Mysterious Mountains",'scraper_provider_id' => 2],
            ["id" => 1556, "name" => "Mysterious Treasures",'scraper_provider_id' => 2],
            ["id" => 4464, "name" => "Mystery of the Fossils",'scraper_provider_id' => 2],
            ["id" => 4069, "name" => "Mythical & Legendary Dream Shine Collection",'scraper_provider_id' => 2],
            ["id" => 4196, "name" => "National Pokédex Beginning Set",'scraper_provider_id' => 2],
            ["id" => 1534, "name" => "Neo Destiny",'scraper_provider_id' => 2],
            ["id" => 1532, "name" => "Neo Discovery",'scraper_provider_id' => 2],
            ["id" => 1531, "name" => "Neo Genesis",'scraper_provider_id' => 2],
            ["id" => 1533, "name" => "Neo Revelation",'scraper_provider_id' => 2],
            ["id" => 1574, "name" => "Next Destinies",'scraper_provider_id' => 2],
            ["id" => 3846, "name" => "Night Unison",'scraper_provider_id' => 2],
            ["id" => 5757, "name" => "Night Wanderer",'scraper_provider_id' => 2],
            ["id" => 6427, "name" => "Nihil Zero",'scraper_provider_id' => 2],
            ["id" => 6204, "name" => "Nine Colors Gathering - Friends",'scraper_provider_id' => 2],
            ["id" => 6205, "name" => "Nine Colors Gathering - Origin",'scraper_provider_id' => 2],
            ["id" => 6494, "name" => "Ninja Spinner",'scraper_provider_id' => 2],
            ["id" => 1608, "name" => "Nintendo Black Star Promos",'scraper_provider_id' => 2],
            ["id" => 5681, "name" => "Nivi City Gym",'scraper_provider_id' => 2],
            ["id" => 1573, "name" => "Noble Victories",'scraper_provider_id' => 2],
            ["id" => 4104, "name" => "Noivern BREAK Evolution Pack",'scraper_provider_id' => 2],
            ["id" => 5385, "name" => "Obsidian Flames",'scraper_provider_id' => 2],
            ["id" => 5699, "name" => "Ocean's Kyogre ex Constructed Starter Deck",'scraper_provider_id' => 2],
            ["id" => 5693, "name" => "Offense and Defense of the Furthest Ends",'scraper_provider_id' => 2],
            ["id" => 4353, "name" => "P Promos",'scraper_provider_id' => 2],
            ["id" => 5318, "name" => "Paldea Evolved",'scraper_provider_id' => 2],
            ["id" => 5546, "name" => "Paldean Fates",'scraper_provider_id' => 2],
            ["id" => 4294, "name" => "Palkia DPt Half Deck",'scraper_provider_id' => 2],
            ["id" => 4311, "name" => "Palkia LV.X Constructed Standard Deck",'scraper_provider_id' => 2],
            ["id" => 5156, "name" => "Paradigm Trigger",'scraper_provider_id' => 2],
            ["id" => 5846, "name" => "Paradise Dragona",'scraper_provider_id' => 2],
            ["id" => 5444, "name" => "Paradox Rift",'scraper_provider_id' => 2],
            ["id" => 4341, "name" => "PCG Promos",'scraper_provider_id' => 2],
            ["id" => 6443, "name" => "Perfect Order",'scraper_provider_id' => 2],
            ["id" => 6516, "name" => "Perfect Order: Additionals",'scraper_provider_id' => 2],
            ["id" => 6299, "name" => "Phantasmal Flames",'scraper_provider_id' => 2],
            ["id" => 6300, "name" => "Phantasmal Flames: Additionals",'scraper_provider_id' => 2],
            ["id" => 1521, "name" => "Phantom Forces",'scraper_provider_id' => 2],
            ["id" => 4044, "name" => "Phantom Gate",'scraper_provider_id' => 2],
            ["id" => 4290, "name" => "Pikachu DPt Half Deck",'scraper_provider_id' => 2],
            ["id" => 6348, "name" => "Pikachu Legendary Celebration",'scraper_provider_id' => 2],
            ["id" => 4392, "name" => "Pikachu World Collection",'scraper_provider_id' => 2],
            ["id" => 3979, "name" => "Pikachu's New Friends",'scraper_provider_id' => 2],
            ["id" => 4291, "name" => "Piplup DPt Half Deck",'scraper_provider_id' => 2],
            ["id" => 1580, "name" => "Plasma Blast",'scraper_provider_id' => 2],
            ["id" => 1579, "name" => "Plasma Freeze",'scraper_provider_id' => 2],
            ["id" => 4193, "name" => "Plasma Gale",'scraper_provider_id' => 2],
            ["id" => 1578, "name" => "Plasma Storm",'scraper_provider_id' => 2],
            ["id" => 1562, "name" => "Platinum",'scraper_provider_id' => 2],
            ["id" => 4349, "name" => "PLAY Promos",'scraper_provider_id' => 2],
            ["id" => 6425, "name" => "Play! Pokémon Prize Pack Series Eight",'scraper_provider_id' => 2],
            ["id" => 5849, "name" => "Play! Pokémon Prize Pack Series Five",'scraper_provider_id' => 2],
            ["id" => 5620, "name" => "Play! Pokémon Prize Pack Series Four",'scraper_provider_id' => 2],
            ["id" => 5204, "name" => "Play! Pokémon Prize Pack Series One",'scraper_provider_id' => 2],
            ["id" => 6214, "name" => "Play! Pokémon Prize Pack Series Seven",'scraper_provider_id' => 2],
            ["id" => 6041, "name" => "Play! Pokémon Prize Pack Series Six",'scraper_provider_id' => 2],
            ["id" => 5431, "name" => "Play! Pokémon Prize Pack Series Three",'scraper_provider_id' => 2],
            ["id" => 5313, "name" => "Play! Pokémon Prize Pack Series Two",'scraper_provider_id' => 2],
            ["id" => 4505, "name" => "Poké Card Creator Pack",'scraper_provider_id' => 2],
            ["id" => 4094, "name" => "PokéKyun Collection",'scraper_provider_id' => 2],
            ["id" => 6302, "name" => "Pokémon Art Illustration Celebration Gathering",'scraper_provider_id' => 2],
            ["id" => 6349, "name" => "Pokémon Art Illustration Celebration Scene",'scraper_provider_id' => 2],
            ["id" => 5328, "name" => "Pokémon Card 151",'scraper_provider_id' => 2],
            ["id" => 6219, "name" => "Pokémon Card 151: Additionals",'scraper_provider_id' => 2],
            ["id" => 6357, "name" => "Pokémon Card Display Set Gift Box Charizard",'scraper_provider_id' => 2],
            ["id" => 6356, "name" => "Pokémon Card Display Set Gift Box Eevee",'scraper_provider_id' => 2],
            ["id" => 5529, "name" => "Pokémon Card Game Classic: Blastoise & Suicune ex Deck",'scraper_provider_id' => 2],
            ["id" => 5528, "name" => "Pokémon Card Game Classic: Charizard & Ho-Oh ex Deck",'scraper_provider_id' => 2],
            ["id" => 5527, "name" => "Pokémon Card Game Classic: Venusaur & Lugia ex Deck",'scraper_provider_id' => 2],
            ["id" => 4168, "name" => "Pokémon Card VS",'scraper_provider_id' => 2],
            ["id" => 4355, "name" => "Pokémon Card web",'scraper_provider_id' => 2],
            ["id" => 5051, "name" => "Pokémon GO",'scraper_provider_id' => 2],
            ["id" => 4786, "name" => "Pokémon GO Enhanced Expansion Pack",'scraper_provider_id' => 2],
            ["id" => 4463, "name" => "Pokémon Jungle",'scraper_provider_id' => 2],
            ["id" => 1645, "name" => "Pokémon Products",'scraper_provider_id' => 2],
            ["id" => 1634, "name" => "Pokémon Rumble",'scraper_provider_id' => 2],
            ["id" => 5532, "name" => "Pokémon Trading Card Game Classic: Blastoise & Suicune ex Deck",'scraper_provider_id' => 2],
            ["id" => 5531, "name" => "Pokémon Trading Card Game Classic: Charizard & Ho-Oh ex Deck",'scraper_provider_id' => 2],
            ["id" => 5530, "name" => "Pokémon Trading Card Game Classic: Venusaur & Lugia ex Deck",'scraper_provider_id' => 2],
            ["id" => 4342, "name" => "PokéPark Blue",'scraper_provider_id' => 2],
            ["id" => 4343, "name" => "PokéPark Forest",'scraper_provider_id' => 2],
            ["id" => 1613, "name" => "POP Series 1",'scraper_provider_id' => 2],
            ["id" => 1614, "name" => "POP Series 2",'scraper_provider_id' => 2],
            ["id" => 1615, "name" => "POP Series 3",'scraper_provider_id' => 2],
            ["id" => 1616, "name" => "POP Series 4",'scraper_provider_id' => 2],
            ["id" => 1617, "name" => "POP Series 5",'scraper_provider_id' => 2],
            ["id" => 1618, "name" => "POP Series 6",'scraper_provider_id' => 2],
            ["id" => 1619, "name" => "POP Series 7",'scraper_provider_id' => 2],
            ["id" => 1620, "name" => "POP Series 8",'scraper_provider_id' => 2],
            ["id" => 1621, "name" => "POP Series 9",'scraper_provider_id' => 2],
            ["id" => 4321, "name" => "PPP Promos",'scraper_provider_id' => 2],
            ["id" => 4074, "name" => "Premium Champion Pack",'scraper_provider_id' => 2],
            ["id" => 4257, "name" => "Premium Trainer Box",'scraper_provider_id' => 2],
            ["id" => 5221, "name" => "Premium Trainer Box ex",'scraper_provider_id' => 2],
            ["id" => 6239, "name" => "Premium Trainer Box MEGA",'scraper_provider_id' => 2],
            ["id" => 4515, "name" => "Premium Trainer Box VSTAR",'scraper_provider_id' => 2],
            ["id" => 6413, "name" => "Presence of Champions",'scraper_provider_id' => 2],
            ["id" => 1585, "name" => "Primal Clash",'scraper_provider_id' => 2],
            ["id" => 6266, "name" => "Primordial Arts - Overgrow",'scraper_provider_id' => 2],
            ["id" => 6267, "name" => "Primordial Arts - Torrent",'scraper_provider_id' => 2],
            ["id" => 5944, "name" => "Prismatic Evolutions",'scraper_provider_id' => 2],
            ["id" => 6009, "name" => "Prismatic Evolutions: Additionals",'scraper_provider_id' => 2],
            ["id" => 3108, "name" => "Professor Program",'scraper_provider_id' => 2],
            ["id" => 2107, "name" => "Promos",'scraper_provider_id' => 2],
            ["id" => 4209, "name" => "Psycho Drive",'scraper_provider_id' => 2],
            ["id" => 5723, "name" => "Quick Construction Packs",'scraper_provider_id' => 2],
            ["id" => 6303, "name" => "Quicksand Card Display Pendant Gift Box",'scraper_provider_id' => 2],
            ["id" => 6272, "name" => "Radiant Energy Vol. 1",'scraper_provider_id' => 2],
            ["id" => 6273, "name" => "Radiant Energy Vol. 2",'scraper_provider_id' => 2],
            ["id" => 6274, "name" => "Radiant Energy Vol. 3",'scraper_provider_id' => 2],
            ["id" => 4009, "name" => "Rage of the Broken Heavens",'scraper_provider_id' => 2],
            ["id" => 5432, "name" => "Raging Surf",'scraper_provider_id' => 2],
            ["id" => 4271, "name" => "Raichu Battle Starter Deck",'scraper_provider_id' => 2],
            ["id" => 4109, "name" => "Raichu BREAK Evolution Pack",'scraper_provider_id' => 2],
            ["id" => 5861, "name" => "Raid Battle",'scraper_provider_id' => 2],
            ["id" => 4315, "name" => "Rampardos the Attacker",'scraper_provider_id' => 2],
            ["id" => 3697, "name" => "Rapid Strike Master",'scraper_provider_id' => 2],
            ["id" => 5727, "name" => "Rayquaza Constructed Starter Deck",'scraper_provider_id' => 2],
            ["id" => 3143, "name" => "Rebel Clash",'scraper_provider_id' => 2],
            ["id" => 3279, "name" => "Rebellion Crash",'scraper_provider_id' => 2],
            ["id" => 4210, "name" => "Red Collection",'scraper_provider_id' => 2],
            ["id" => 4019, "name" => "Red Flash",'scraper_provider_id' => 2],
            ["id" => 4281, "name" => "Regigigas LV.X Collection Pack",'scraper_provider_id' => 2],
            ["id" => 3811, "name" => "Remix Bout",'scraper_provider_id' => 2],
            ["id" => 4207, "name" => "Reshiram EX Battle Strength Deck",'scraper_provider_id' => 2],
            ["id" => 6275, "name" => "Return of the Dragon",'scraper_provider_id' => 2],
            ["id" => 4265, "name" => "Reviving Legends",'scraper_provider_id' => 2],
            ["id" => 4049, "name" => "Rising Fist",'scraper_provider_id' => 2],
            ["id" => 1563, "name" => "Rising Rivals",'scraper_provider_id' => 2],
            ["id" => 1649, "name" => "Roaring Skies",'scraper_provider_id' => 2],
            ["id" => 4465, "name" => "Rocket Gang",'scraper_provider_id' => 2],
            ["id" => 5712, "name" => "Rocket Gang Strikes Back",'scraper_provider_id' => 2],
            ["id" => 4256, "name" => "Rockruff Full Power Deck",'scraper_provider_id' => 2],
            ["id" => 5409, "name" => "Ruler of the Black Flame",'scraper_provider_id' => 2],
            ["id" => 5422, "name" => "Ruler of the Black Flame Deck Build Box",'scraper_provider_id' => 2],
            ["id" => 5872, "name" => "Rulers of the Heavens",'scraper_provider_id' => 2],
            ["id" => 5870, "name" => "Salamence Constructed Starter Deck",'scraper_provider_id' => 2],
            ["id" => 5223, "name" => "Scarlet & Violet",'scraper_provider_id' => 2],
            ["id" => 5621, "name" => "Scarlet & Violet Battle Academy",'scraper_provider_id' => 2],
            ["id" => 5224, "name" => "Scarlet & Violet Energies",'scraper_provider_id' => 2],
            ["id" => 5351, "name" => "Scarlet & Violet ex Special Set",'scraper_provider_id' => 2],
            ["id" => 6127, "name" => "Scarlet & Violet Indonesian Promos",'scraper_provider_id' => 2],
            ["id" => 5335, "name" => "Scarlet & Violet Products",'scraper_provider_id' => 2],
            ["id" => 5212, "name" => "Scarlet & Violet Promos",'scraper_provider_id' => 2],
            ["id" => 6328, "name" => "Scarlet & Violet Simplified Chinese Promos",'scraper_provider_id' => 2],
            ["id" => 6128, "name" => "Scarlet & Violet Thai Promos",'scraper_provider_id' => 2],
            ["id" => 5216, "name" => "Scarlet ex",'scraper_provider_id' => 2],
            ["id" => 6265, "name" => "Scorching Skies",'scraper_provider_id' => 2],
            ["id" => 4317, "name" => "Secret of the Lakes",'scraper_provider_id' => 2],
            ["id" => 1557, "name" => "Secret Wonders",'scraper_provider_id' => 2],
            ["id" => 6248, "name" => "Shadow of Glory",'scraper_provider_id' => 2],
            ["id" => 4283, "name" => "Shaymin LV.X Collection Pack",'scraper_provider_id' => 2],
            ["id" => 3294, "name" => "Shield",'scraper_provider_id' => 2],
            ["id" => 4313, "name" => "Shining Darkness",'scraper_provider_id' => 2],
            ["id" => 3630, "name" => "Shining Fates",'scraper_provider_id' => 2],
            ["id" => 1842, "name" => "Shining Legends",'scraper_provider_id' => 2],
            ["id" => 3931, "name" => "Shining Legends JP",'scraper_provider_id' => 2],
            ["id" => 6369, "name" => "Shining Pokémon Poké Ball Box",'scraper_provider_id' => 2],
            ["id" => 6319, "name" => "Shining Synergy - Shower",'scraper_provider_id' => 2],
            ["id" => 6321, "name" => "Shining Synergy - Summon",'scraper_provider_id' => 2],
            ["id" => 6320, "name" => "Shining Synergy - Supreme",'scraper_provider_id' => 2],
            ["id" => 4184, "name" => "Shiny Collection",'scraper_provider_id' => 2],
            ["id" => 3580, "name" => "Shiny Star V",'scraper_provider_id' => 2],
            ["id" => 5519, "name" => "Shiny Treasure ex",'scraper_provider_id' => 2],
            ["id" => 3479, "name" => "Shocking Volt Tackle",'scraper_provider_id' => 2],
            ["id" => 5694, "name" => "Shockwave! Tyranitar ex Constructed Standard Deck",'scraper_provider_id' => 2],
            ["id" => 5760, "name" => "Shrouded Fable",'scraper_provider_id' => 2],
            ["id" => 5725, "name" => "Silver Deck Kit",'scraper_provider_id' => 2],
            ["id" => 4171, "name" => "Silver Lance",'scraper_provider_id' => 2],
            ["id" => 4173, "name" => "Silver Lance & Jet Black Spirit Jumbo Pack Set",'scraper_provider_id' => 2],
            ["id" => 5142, "name" => "Silver Tempest",'scraper_provider_id' => 2],
            ["id" => 3717, "name" => "Single Strike & Rapid Strike Premium Trainer Boxes",'scraper_provider_id' => 2],
            ["id" => 3712, "name" => "Single Strike Master",'scraper_provider_id' => 2],
            ["id" => 3821, "name" => "Sky Legend",'scraper_provider_id' => 2],
            ["id" => 3881, "name" => "Sky-Splitting Charisma",'scraper_provider_id' => 2],
            ["id" => 1538, "name" => "Skyridge",'scraper_provider_id' => 2],
            ["id" => 1757, "name" => "SM Black Star Promos",'scraper_provider_id' => 2],
            ["id" => 2070, "name" => "SM Trainer Kit: Alolan Sandslash & Alolan Ninetales",'scraper_provider_id' => 2],
            ["id" => 1758, "name" => "SM Trainer Kit: Lycanroc & Alolan Raichu",'scraper_provider_id' => 2],
            ["id" => 5314, "name" => "Snow Hazard",'scraper_provider_id' => 2],
            ["id" => 4254, "name" => "Solgaleo GX & Lunala GX Legendary Starter Set",'scraper_provider_id' => 2],
            ["id" => 4272, "name" => "SoulSilver Collection",'scraper_provider_id' => 2],
            ["id" => 5834, "name" => "Southeast Asia Promos",'scraper_provider_id' => 2],
            ["id" => 1633, "name" => "Southern Islands",'scraper_provider_id' => 2],
            ["id" => 4357, "name" => "Southern Islands JP",'scraper_provider_id' => 2],
            ["id" => 4974, "name" => "Space Juggler",'scraper_provider_id' => 2],
            ["id" => 4318, "name" => "Space-Time Creation",'scraper_provider_id' => 2],
            ["id" => 5179, "name" => "Special Battle Set Charizard VSTAR vs Rayquaza VMAX",'scraper_provider_id' => 2],
            ["id" => 4385, "name" => "Special Deck Set Zacian Zamazenta vs Eternatus",'scraper_provider_id' => 2],
            ["id" => 4186, "name" => "Spiral Force",'scraper_provider_id' => 2],
            ["id" => 5024, "name" => "Split Earth",'scraper_provider_id' => 2],
            ["id" => 4440, "name" => "Star Birth",'scraper_provider_id' => 2],
            ["id" => 4388, "name" => "Start Deck 100",'scraper_provider_id' => 2],
            ["id" => 4518, "name" => "Start Deck 100 CoroCoro Comic Version",'scraper_provider_id' => 2],
            ["id" => 5575, "name" => "Starter Deck & Build Set Ancient Koraidon ex",'scraper_provider_id' => 2],
            ["id" => 5576, "name" => "Starter Deck & Build Set Future Miraidon ex",'scraper_provider_id' => 2],
            ["id" => 6016, "name" => "Starter Set ex Marnie's Morpeko & Grimmsnarl ex",'scraper_provider_id' => 2],
            ["id" => 6017, "name" => "Starter Set ex Steven's Beldum & Metagross ex",'scraper_provider_id' => 2],
            ["id" => 1716, "name" => "Steam Siege",'scraper_provider_id' => 2],
            ["id" => 4264, "name" => "Steelix Constructed Standard Deck",'scraper_provider_id' => 2],
            ["id" => 5802, "name" => "Stellar Crown",'scraper_provider_id' => 2],
            ["id" => 6419, "name" => "Stellar Lightning",'scraper_provider_id' => 2],
            ["id" => 5782, "name" => "Stellar Miracle",'scraper_provider_id' => 2],
            ["id" => 5835, "name" => "Stellar Miracle Deck Build Box",'scraper_provider_id' => 2],
            ["id" => 5842, "name" => "Stellar Tera Type Starter Set Ceruledge ex",'scraper_provider_id' => 2],
            ["id" => 5841, "name" => "Stellar Tera Type Starter Set Sylveon ex",'scraper_provider_id' => 2],
            ["id" => 1561, "name" => "Stormfront",'scraper_provider_id' => 2],
            ["id" => 6343, "name" => "Storming Emergence - Abundant",'scraper_provider_id' => 2],
            ["id" => 6341, "name" => "Storming Emergence - Radiant",'scraper_provider_id' => 2],
            ["id" => 6342, "name" => "Storming Emergence - Verdant",'scraper_provider_id' => 2],
            ["id" => 3961, "name" => "Strength Expansion Pack Sun & Moon",'scraper_provider_id' => 2],
            ["id" => 6313, "name" => "Striking Competition",'scraper_provider_id' => 2],
            ["id" => 1745, "name" => "Sun & Moon",'scraper_provider_id' => 2],
            ["id" => 4246, "name" => "Sun & Moon Family Pokémon Card Game",'scraper_provider_id' => 2],
            ["id" => 5415, "name" => "Sun & Moon Products",'scraper_provider_id' => 2],
            ["id" => 3324, "name" => "Sun & Moon Promos",'scraper_provider_id' => 2],
            ["id" => 6330, "name" => "Sun & Moon Simplified Chinese Promos",'scraper_provider_id' => 2],
            ["id" => 4258, "name" => "Sun & Moon Starter Set",'scraper_provider_id' => 2],
            ["id" => 5901, "name" => "Super Electric Breaker",'scraper_provider_id' => 2],
            ["id" => 4129, "name" => "Super Legend Set: Xerneas EX & Yveltal EX",'scraper_provider_id' => 2],
            ["id" => 3866, "name" => "Super-Burst Impact",'scraper_provider_id' => 2],
            ["id" => 1564, "name" => "Supreme Victors",'scraper_provider_id' => 2],
            ["id" => 5879, "name" => "Surging Sparks",'scraper_provider_id' => 2],
            ["id" => 5241, "name" => "SV Black Star Promos",'scraper_provider_id' => 2],
            ["id" => 3289, "name" => "Sword",'scraper_provider_id' => 2],
            ["id" => 2921, "name" => "Sword & Shield",'scraper_provider_id' => 2],
            ["id" => 4243, "name" => "Sword & Shield Family Pokémon Card Game",'scraper_provider_id' => 2],
            ["id" => 3615, "name" => "Sword & Shield Premium Trainer Box",'scraper_provider_id' => 2],
            ["id" => 5798, "name" => "Sword & Shield Products",'scraper_provider_id' => 2],
            ["id" => 3214, "name" => "Sword & Shield Promos",'scraper_provider_id' => 2],
            ["id" => 6329, "name" => "Sword & Shield Simplified Chinese Promos",'scraper_provider_id' => 2],
            ["id" => 3600, "name" => "Sword & Shield Starter Decks",'scraper_provider_id' => 2],
            ["id" => 4517, "name" => "Sword & Shield Starter Set Darkrai VSTAR",'scraper_provider_id' => 2],
            ["id" => 4516, "name" => "Sword & Shield Starter Set Lucario VSTAR",'scraper_provider_id' => 2],
            ["id" => 6354, "name" => "Sword & Shield Trainer Collection Gift Box",'scraper_provider_id' => 2],
            ["id" => 2916, "name" => "SWSH Black Star Promos",'scraper_provider_id' => 2],
            ["id" => 4354, "name" => "T Promos",'scraper_provider_id' => 2],
            ["id" => 3851, "name" => "Tag Bolt",'scraper_provider_id' => 2],
            ["id" => 4247, "name" => "Tag Team GX Deck Build Box",'scraper_provider_id' => 2],
            ["id" => 4249, "name" => "Tag Team GX Premium Trainer Box",'scraper_provider_id' => 2],
            ["id" => 4245, "name" => "Tag Team GX Starter Sets",'scraper_provider_id' => 2],
            ["id" => 3776, "name" => "Tag Team GX: Tag All Stars",'scraper_provider_id' => 2],
            ["id" => 5684, "name" => "Tamamushi City Gym",'scraper_provider_id' => 2],
            ["id" => 4255, "name" => "Tapu Bulu GX Enhanced Starter Set",'scraper_provider_id' => 2],
            ["id" => 4188, "name" => "Team Plasma Battle Gift Set",'scraper_provider_id' => 2],
            ["id" => 4192, "name" => "Team Plasma's Powered Half Deck",'scraper_provider_id' => 2],
            ["id" => 1528, "name" => "Team Rocket",'scraper_provider_id' => 2],
            ["id" => 2407, "name" => "Team Up",'scraper_provider_id' => 2],
            ["id" => 4304, "name" => "Temple of Anger",'scraper_provider_id' => 2],
            ["id" => 5589, "name" => "Temporal Forces",'scraper_provider_id' => 2],
            ["id" => 5928, "name" => "Terastal Festival ex",'scraper_provider_id' => 2],
            ["id" => 6220, "name" => "Terastal Festival ex: Additionals",'scraper_provider_id' => 2],
            ["id" => 5477, "name" => "Terastal Starter Set Mewtwo ex",'scraper_provider_id' => 2],
            ["id" => 5476, "name" => "Terastal Starter Set Skeledirge ex",'scraper_provider_id' => 2],
            ["id" => 3984, "name" => "The Best of XY",'scraper_provider_id' => 2],
            ["id" => 6092, "name" => "The Glory of Team Rocket",'scraper_provider_id' => 2],
            ["id" => 5022, "name" => "The Town on No Map",'scraper_provider_id' => 2],
            ["id" => 4351, "name" => "Theater Limited VS Pack",'scraper_provider_id' => 2],
            ["id" => 4185, "name" => "Thunder Knuckle",'scraper_provider_id' => 2],
            ["id" => 3876, "name" => "Thunderclap Spark",'scraper_provider_id' => 2],
            ["id" => 4034, "name" => "Tidal Storm",'scraper_provider_id' => 2],
            ["id" => 4973, "name" => "Time Gazer",'scraper_provider_id' => 2],
            ["id" => 3941, "name" => "To Have Seen the Battle Rainbow",'scraper_provider_id' => 2],
            ["id" => 5875, "name" => "Torchic Constructed Starter Deck",'scraper_provider_id' => 2],
            ["id" => 4268, "name" => "Torterra Battle Starter Deck",'scraper_provider_id' => 2],
            ["id" => 4329, "name" => "Towering Perfection",'scraper_provider_id' => 2],
            ["id" => 5960, "name" => "Traditional Chinese Products",'scraper_provider_id' => 2],
            ["id" => 4248, "name" => "Trainer Battle Decks",'scraper_provider_id' => 2],
            ["id" => 6361, "name" => "Travel Special Pack",'scraper_provider_id' => 2],
            ["id" => 5876, "name" => "Treecko Constructed Starter Deck",'scraper_provider_id' => 2],
            ["id" => 5138, "name" => "Trick or Trade",'scraper_provider_id' => 2],
            ["id" => 5405, "name" => "Trick or Trade 2023",'scraper_provider_id' => 2],
            ["id" => 5796, "name" => "Trick or Trade 2024",'scraper_provider_id' => 2],
            ["id" => 5257, "name" => "Triplet Beat",'scraper_provider_id' => 2],
            ["id" => 1569, "name" => "Triumphant",'scraper_provider_id' => 2],
            ["id" => 6362, "name" => "True Mystery",'scraper_provider_id' => 2],
            ["id" => 4292, "name" => "Turtwig DPt Half Deck",'scraper_provider_id' => 2],
            ["id" => 5691, "name" => "Twilight Masquerade",'scraper_provider_id' => 2],
            ["id" => 5721, "name" => "Typhlosion Constructed Starter Deck",'scraper_provider_id' => 2],
            ["id" => 4263, "name" => "Tyranitar Constructed Standard Deck",'scraper_provider_id' => 2],
            ["id" => 3901, "name" => "Ultra Force",'scraper_provider_id' => 2],
            ["id" => 3906, "name" => "Ultra Moon",'scraper_provider_id' => 2],
            ["id" => 2065, "name" => "Ultra Prism",'scraper_provider_id' => 2],
            ["id" => 3911, "name" => "Ultra Sun",'scraper_provider_id' => 2],
            ["id" => 4252, "name" => "Ultra Sun & Ultra Moon Deck Build Boxes",'scraper_provider_id' => 2],
            ["id" => 4253, "name" => "Ultra Sun & Ultra Moon Premium Trainer Box",'scraper_provider_id' => 2],
            ["id" => 3921, "name" => "Ultradimensional Beasts",'scraper_provider_id' => 2],
            ["id" => 2437, "name" => "Unbroken Bonds",'scraper_provider_id' => 2],
            ["id" => 1568, "name" => "Undaunted",'scraper_provider_id' => 2],
            ["id" => 5864, "name" => "Undone Seal",'scraper_provider_id' => 2],
            ["id" => 2487, "name" => "Unified Minds",'scraper_provider_id' => 2],
            ["id" => 1567, "name" => "Unleashed",'scraper_provider_id' => 2],
            ["id" => 4170, "name" => "Unnumbered Promos",'scraper_provider_id' => 2],
            ["id" => 3389, "name" => "V Starter Decks",'scraper_provider_id' => 2],
            ["id" => 4381, "name" => "V-UNION Special Card Sets",'scraper_provider_id' => 2],
            ["id" => 6355, "name" => "Variety Treasure Box",'scraper_provider_id' => 2],
            ["id" => 5525, "name" => "Venusaur & Charizard & Blastoise Special Deck Set ex",'scraper_provider_id' => 2],
            ["id" => 5729, "name" => "Venusaur, Charizard & Blastoise Random Constructed Starter Decks",'scraper_provider_id' => 2],
            ["id" => 6247, "name" => "Victory Star Guide",'scraper_provider_id' => 2],
            ["id" => 5217, "name" => "Violet ex",'scraper_provider_id' => 2],
            ["id" => 6281, "name" => "Vivid Portrayals - Indigo",'scraper_provider_id' => 2],
            ["id" => 6279, "name" => "Vivid Portrayals - Obsidian",'scraper_provider_id' => 2],
            ["id" => 3484, "name" => "Vivid Voltage",'scraper_provider_id' => 2],
            ["id" => 4390, "name" => "VMAX Climax",'scraper_provider_id' => 2],
            ["id" => 3284, "name" => "VMAX Rising",'scraper_provider_id' => 2],
            ["id" => 3610, "name" => "VMAX Special Set",'scraper_provider_id' => 2],
            ["id" => 3590, "name" => "VMAX Starter Deck: Blastoise VMAX",'scraper_provider_id' => 2],
            ["id" => 3585, "name" => "VMAX Starter Deck: Venusaur VMAX",'scraper_provider_id' => 2],
            ["id" => 3595, "name" => "VMAX Starter Decks",'scraper_provider_id' => 2],
            ["id" => 5097, "name" => "VSTAR & VMAX High Class Deck Deoxys",'scraper_provider_id' => 2],
            ["id" => 5096, "name" => "VSTAR & VMAX High Class Deck Zeraora",'scraper_provider_id' => 2],
            ["id" => 5098, "name" => "VSTAR Special Set",'scraper_provider_id' => 2],
            ["id" => 5198, "name" => "VSTAR Universe",'scraper_provider_id' => 2],
            ["id" => 1753, "name" => "WCD 2004",'scraper_provider_id' => 2],
            ["id" => 1754, "name" => "WCD 2005",'scraper_provider_id' => 2],
            ["id" => 1755, "name" => "WCD 2006",'scraper_provider_id' => 2],
            ["id" => 1756, "name" => "WCD 2007",'scraper_provider_id' => 2],
            ["id" => 2027, "name" => "WCD 2008",'scraper_provider_id' => 2],
            ["id" => 2028, "name" => "WCD 2009",'scraper_provider_id' => 2],
            ["id" => 2026, "name" => "WCD 2010",'scraper_provider_id' => 2],
            ["id" => 2395, "name" => "WCD 2011",'scraper_provider_id' => 2],
            ["id" => 2749, "name" => "WCD 2012",'scraper_provider_id' => 2],
            ["id" => 2744, "name" => "WCD 2013",'scraper_provider_id' => 2],
            ["id" => 2754, "name" => "WCD 2014",'scraper_provider_id' => 2],
            ["id" => 2029, "name" => "WCD 2015",'scraper_provider_id' => 2],
            ["id" => 2394, "name" => "WCD 2016",'scraper_provider_id' => 2],
            ["id" => 2393, "name" => "WCD 2017",'scraper_provider_id' => 2],
            ["id" => 2396, "name" => "WCD 2018",'scraper_provider_id' => 2],
            ["id" => 2739, "name" => "WCD 2019",'scraper_provider_id' => 2],
            ["id" => 6203, "name" => "WCD 2022",'scraper_provider_id' => 2],
            ["id" => 6194, "name" => "WCD 2023",'scraper_provider_id' => 2],
            ["id" => 5992, "name" => "WCD 2024",'scraper_provider_id' => 2],
            ["id" => 4213, "name" => "White Collection",'scraper_provider_id' => 2],
            ["id" => 6135, "name" => "White Flare",'scraper_provider_id' => 2],
            ["id" => 6131, "name" => "White Flare JP",'scraper_provider_id' => 2],
            ["id" => 6223, "name" => "White Flare JP: Additionals",'scraper_provider_id' => 2],
            ["id" => 6198, "name" => "White Flare: Additionals",'scraper_provider_id' => 2],
            ["id" => 4189, "name" => "White Kyurem EX Battle Strength Deck",'scraper_provider_id' => 2],
            ["id" => 4054, "name" => "Wild Blaze",'scraper_provider_id' => 2],
            ["id" => 5573, "name" => "Wild Force",'scraper_provider_id' => 2],
            ["id" => 5023, "name" => "Wind from the Sea",'scraper_provider_id' => 2],
            ["id" => 1607, "name" => "Wizards Black Star Promos",'scraper_provider_id' => 2],
            ["id" => 4314, "name" => "World Champions Pack",'scraper_provider_id' => 2],
            ["id" => 5410, "name" => "World Championships 2023 Yokohama Deck -Pikachu-",'scraper_provider_id' => 2],
            ["id" => 4149, "name" => "Xerneas Half Deck",'scraper_provider_id' => 2],
            ["id" => 1582, "name" => "XY",'scraper_provider_id' => 2],
            ["id" => 4154, "name" => "XY Beginning Set",'scraper_provider_id' => 2],
            ["id" => 1612, "name" => "XY Black Star Promos",'scraper_provider_id' => 2],
            ["id" => 1637, "name" => "XY Kalos Starter Set",'scraper_provider_id' => 2],
            ["id" => 4159, "name" => "XY Promos",'scraper_provider_id' => 2],
            ["id" => 1631, "name" => "XY Trainer Kit",'scraper_provider_id' => 2],
            ["id" => 1632, "name" => "XY Trainer Kit: Bisharp & Wigglytuff",'scraper_provider_id' => 2],
            ["id" => 1683, "name" => "XY Trainer Kit: Latias & Latios",'scraper_provider_id' => 2],
            ["id" => 1707, "name" => "XY Trainer Kit: Pikachu Libre & Suicune",'scraper_provider_id' => 2],
            ["id" => 5685, "name" => "Yamabuki City Gym",'scraper_provider_id' => 2],
            ["id" => 4144, "name" => "Yveltal Half Deck",'scraper_provider_id' => 2],
            ["id" => 3605, "name" => "Zacian + Zamazenta BOX",'scraper_provider_id' => 2],
            ["id" => 4206, "name" => "Zekrom EX Battle Strength Deck",'scraper_provider_id' => 2],
            ["id" => 4084, "name" => "Zygarde EX Perfect Battle Deck",'scraper_provider_id' => 2],
        ];

        // L'upsert permette di lanciare il seeder più volte aggiornando eventuali nomi cambiati,
        // basandosi sulla chiave primaria 'id'.
        DB::table('scraping_expansions')->upsert(
            $expansions,
            ['id','scraper_provider_id' => 2], // Colonne univoque
            ['name'] // Colonne da aggiornare se l'ID esiste già
        );
    }
}
